version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - ./dev.env
  web:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./dev.env
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - POSTGRES_HOST=postgres
    volumes:
      - ./app:/opt/app
    depends_on:
      - postgres
volumes:
  postgres-volume:
    external: true